name: Build and Push Docker Image to Docker Hub

on: push
jobs:
  push_to_registry:
    name: Push Docker Image to Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push Docker Image to Registry
        uses: docker/build-push-action@v5
        with:
          context: ./e-commerce-frontend-main  # Adjust this path as needed
          file: ./e-commerce-frontend-main/Dockerfile  # Specify the Dockerfile if needed
          push: true
          tags: black1512/demo1:latest
